## Build target image

FROM hbpmip/python-sgd-regression

ENV DOCKER_IMAGE=hbpmip/python-sgd-naive-bayes:0.3.3 \
    FUNCTION=python-sgd-naive-bayes \
    MODEL_PARAM_type=naive_bayes

ENTRYPOINT ["python", "/sgd_regression.py"]

LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name="hbpmip/python-sgd-naive-bayes" \
      org.label-schema.description="Python implementation of sgd-regression" \
      org.label-schema.url="https://github.com/LREN-CHUV/algorithm-repository" \
      org.label-schema.vcs-type="git" \
      org.label-schema.vcs-url="https://github.com/LREN-CHUV/algorithm-repository.git" \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.version="$VERSION" \
      org.label-schema.vendor="LREN CHUV" \
      org.label-schema.license="AGPLv3" \
      org.label-schema.docker.dockerfile="Dockerfile" \
      org.label-schema.schema-version="1.0"
